name: Quizrise Backend CI/CD Pipeline

on:
  push:
    branches: [ "main", "dev" ]        # chạy khi push vào nhánh main hoặc dev
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build-and-deploy: # 
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Login Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Build & push image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: giatrong/quizrise-fe

      # # 4. Deploy trên Linux server qua SSH
      # - name: Deploy to Linux server
      #   uses: appleboy/ssh-action@v1.0.3
      #   with:
      #     host: ${{ secrets.SERVER_HOST }}
      #     username: ${{ secrets.SERVER_USER }}
      #     key: ${{ secrets.SERVER_SSH_KEY }}
      #     script: |
      #       cd ~/quiz
      #       docker compose -f docker-compose.yml --env-file .env pull
      #       docker compose -f docker-compose.yml --env-file .env up -d